### ISSUE TITLE
Integration fails to load

### ISSUE THREAD

**Issue by ChrisThomas42** [AlexandrErohin/home-assistant-flightradar24#134]
**Describe the bug**
Integration failed to start.

I am getting this error after upgrade to 2025.0 and after "some" restarts of HA.  Sometimes another restart after a few minutes will clear the error, but a restart does not always clear the error.  There is no reload integration option shown and a HA restart is the only option.

**Logs**
Logger: homeassistant.setup
Source: setup.py:344
First occurred: 08:52:11 (1 occurrence)
Last logged: 08:52:11

Setup failed for custom integration 'flightradar24': Unable to import component: cannot import name 'countries' from 'pycountry' (unknown location)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 993, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1053, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/flightradar24/__init__.py", line 7, in <module>
    from .coordinator import FlightRadar24Coordinator
  File "/config/custom_components/flightradar24/coordinator.py", line 8, in <module>
    from pycountry import countries
ImportError: cannot import name 'countries' from 'pycountry' (unknown location)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 344, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1013, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1005, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1053, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/flightradar24/__init__.py", line 7, in <module>
    from .coordinator import FlightRadar24Coordinator
  File "/config/custom_components/flightradar24/coordinator.py", line 8, in <module>
    from pycountry import countries
ImportError: cannot import name 'countries' from 'pycountry' (unknown location)

**Comment by AlexandrErohin** [comment]
This error means that while update HA had not install python module - pycountry. The reason why HA had not install the module not in this integration.

**Comment by nathan-curtis** [comment]
Uninstalled FR. Ran repair install on ha core. Restarted reinstalled FR24. So far ok.

**Comment by Nickduino** [comment]
> This error means that while update HA had not install python module - pycountry. The reason why HA had not install the module not in this integration.

But why does it work after a restart if a module is missing, then?

<img width="676" height="393" alt="Image" src="https://github.com/user-attachments/assets/9591eb84-c5bf-4da5-85aa-40ec6517cab6" />



Is pycountry used to display the flags? Because they're working:

<img width="482" height="132" alt="Image" src="https://github.com/user-attachments/assets/a9ff5000-251c-4956-9661-1c074501ab0f" />

**Comment by fgibaux** [comment]
isn't it the case that the requirement needs to be more flexible?

at the moment, it's 
```
"requirements": ["FlightRadarAPI==1.3.34", "pycountry==23.12.11"],
```

since I updated Home Assistant to 2025.11.3 I'm consistently getting the same error and it doesn't load.

I updated the requirement on my system to be 

```
"requirements": ["FlightRadarAPI==1.3.34","pycountry>23.12.10" ],
```

and it loaded.

**Comment by iAmRenzo** [comment]
> > This error means that while update HA had not install python module - pycountry. The reason why HA had not install the module not in this integration.
> 
> But why does it work after a restart if a module is missing, then?
> 
> <img alt="Image" width="676" height="393" src="https://private-user-images.githubusercontent.com/9784237/477760490-9591eb84-c5bf-4da5-85aa-40ec6517cab6.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ2NjIzMjgsIm5iZiI6MTc2NDY2MjAyOCwicGF0aCI6Ii85Nzg0MjM3LzQ3Nzc2MDQ5MC05NTkxZWI4NC1jNWJmLTRkYTUtODVhYS00MGVjNjUxN2NhYjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEyMDJUMDc1MzQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2Q2NWE3ZTBiZmQxYzYwNDBiOWZiY2U5YmJlN2M5NGViMmNiMWQwZWQxMzMxYzJkZDE1OGQ2OTYyZWJiZDQzMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.JGMUnsSbfUwjXzckaDImwGJ_5PVY-rI-sG5tQBd-5YI">
> Is pycountry used to display the flags? Because they're working:
> 
> <img alt="Image" width="482" height="132" src="https://private-user-images.githubusercontent.com/9784237/477760948-a9ff5000-251c-4956-9661-1c074501ab0f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ2NjIzMjgsIm5iZiI6MTc2NDY2MjAyOCwicGF0aCI6Ii85Nzg0MjM3LzQ3Nzc2MDk0OC1hOWZmNTAwMC0yNTFjLTQ5NTYtOTY2MS0xYzA3NDUwMWFiMGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEyMDJUMDc1MzQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDQ2NmI5Y2YzZWIzMDg3MGIwNThlZGU1NWJhNDFiOTlkODUxNWNjMjQ5NTkzZTAxZTM5Yjk5MWE5ODcxMDllZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.UECYvBP4zY3vpiOHy7gypuBEckip0HrSHIHibrv7X5I">

I experience this too. FlightRadar24 randomly unavailable while rebooting HA. After the next reboot usually back. A "reload" option in the cog-menu would be great...
