### ISSUE TITLE
Error setting up entry FlightRadar24 for flightradar24 in HA 2025.3.2

### ISSUE THREAD

**Issue by ronvwier** [AlexandrErohin/home-assistant-flightradar24#119]
Was working in HA versions before 2025.3.1, now doesn't load

Logger: homeassistant.config_entries
Bron: config_entries.py:753
Eerst voorgekomen: 13 maart 2025 om 15:58:37 (3 gebeurtenissen)
Laatst gelogd: 12:30:59

Error setting up entry FlightRadar24 for flightradar24
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 753, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/flightradar24/__init__.py", line 64, in async_setup_entry
    coordinator.tracked = get_restore_state(hass, entry)
                          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/config/custom_components/flightradar24/__init__.py", line 93, in get_restore_state
    state = last_states.get(entr.entity_id).state.attributes.get('flights')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'state'

**Comment by ronvwier** [comment]
A restart doesn't help. Done multiple, even restarting the whole machine.

**Comment by ronvwier** [comment]
Problem solved after:

1. remove flightradar24 from integrations
2. restart HA
3. add flightradar24 as integration
